# Generated by Django 4.2.4 on 2023-09-14 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_productdetails_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='images',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/products'),
            preserve_default=False,
        ),
    ]
