# Generated by Django 4.2.3 on 2023-09-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_image_image_image_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='feature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ProductDetails',
        ),
    ]
