# Generated by Django 4.2.3 on 2023-10-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='COCAINJESUS', max_length=100, null=True),
        ),
    ]
